### ISSUE TITLE
Support check_mode for modules

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#134]
If the user runs Ansible in check mode, a module should try to predict and report whether changes will occur but not actually make any changes (modules that do not support check mode will also take no action, but just will not report what changes they might have made).

Resources: [Ansible Documentation](https://docs.ansible.com/ansible/2.3/dev_guide/developing_modules_general.html#supporting-check-mode)

Example
-------

```python
module = AnsibleModule(
    argument_spec = dict(...),
    supports_check_mode=True
)

if module.check_mode:
    # Check if any changes would be made but don't actually make those changes
    module.exit_json(changed=check_if_system_state_would_be_changed())
```

**Comment by freedge** [comment]
hi

I am correct saying the check_mode is not supported, even though the modules like cv_configlet claim to support it?

Apart from that is it possible to try to align the semantic of this module with the one of eos_config or the rest of the networking modules, so that:
- it is the job of cv_configlet to retrieve the facts it needs, the user should not have to call a cv_facts before hand
- in general cv_facts retrieve all configlets, so this does not scale if we have thousands of those
- configlet_filter and state seem redundant..

I may be missing completely the usecase of this module or of configlets, I would have expected to just write:
```
- cv_configlet:
        configlets: "{{configlet_list}}"
        configlets_notes: "Configlet managed by Ansible"
        state: present
```

run in --diff mode, it would give me the diff between the desired state of my configlet_list and the one already existing, keeping the rest of the configlets alone. And if I run in check mode it just does nothing but a diff.

Cheers!

**Comment by titom73** [comment]
Hello @freedge 

You are correct with `check_mode` support. There is a work-in-progress to implement full support of this feature and it will be pushed later in the repository in a futur version unless a PR provides such support.

As you mentioned, `cv_facts` collects a large amount of information since it is the baseline to compute all the changes modules can do.

For isntance, since all modules are intend based, it is expected to provide list of configlets to configure on CV. So ansible needs to know all current configlets to optionaly remove some of them.

In example you provide, [`arista.cvp.cv_configlet`](https://cvp.avd.sh/docs/modules/cv_configlet.rst/) will try to delete all configlets not part of your list.

Beside that, `configlet_filter` and `state` are not doing the same job:

- `configlet_filter` limit scope of intend based to configlets matching this filter. It is important if we don't want to manage all configlets with ansible.
- `state` define if ansible should create/update or delete list you provide with `{{ configlet_list }}`

**Comment by freedge** [comment]
just checked the devel branch, it works, thanks!

I am displaying the diff with

```
    - debug:
        msg: "{{ configletres.diff.split('\n') }}"
```

btw, there is something annoying with the line ending. It looks like the configlets (I guess, defined through the cvp GUI) had the \r\n DOS style, when executing the cv_configlet task (on a Linux machine), it finds \n as line ending, and give me a gigantic diff. This ends up creating task in CVP with 0 line change, but if you look at the history of the configlet, it completely messes up the diff there.

Is it possible to somehow make something coherent for the line ending handling in cvp?

**Comment by titom73** [comment]
Hello @freedge 

Thanks for the feedback. It will be tracked under issue #266 as it is a new change not related to pure `--check` mode since you can get diff in a general way.
