### ISSUE TITLE
Better handling of secrets

### ISSUE THREAD

**Issue by freedge** [aristanetworks/ansible-cvp#271]
I would like to achieve 2 things:
First we have a "AAA configlet" to centralize user secrets and tacacs config. As this is sensitive information, I would like to not retrieve it systematically when calling cv_facts (generally I believe these secrets should never be displayed but reality is deceiving).

Second I see there is a (world readable) /tmp/arista.cvp.debug.log that also contains these secrets.

I don't think it's easy to sanitize that log file (ideally, CVP should not return this info anyway), but would it be possible to have a list of the configlets we want to retrieve or something similar? It would make cv_facts faster and would reduce the risk of retrieving sensitive stuff.

**Comment by titom73** [comment]
Hello @freedge 

Unfortunately, the Ansible module needs to collect all configlets since ansible will build a list of changes to do during the playbook execution.

As it is 2 API calls, getting all the configlets should not impact execution performance. 

I understand security concerns so we will update module logging to not log the content of configlets and see if we can set no log file per default. 

Besides that, since Ansible is using a CV username, it means if this user can access CV to read the same secret and same on EOS devices. So hiding these secrets will complexify overall modules execution especially to run configlet diff.
