### ISSUE TITLE
Copy CVP JSON into facts as is

### ISSUE THREAD

**Issue by networkop** [aristanetworks/ansible-cvp#30]
I've noticed we've been filtering what data is being copied from JSON received from CVP into CVP facts, e.g. https://github.com/aristanetworks/ansible-cvp/blob/grant-release/library/cv_configlet.py#L281
This creates several problems:
1. Our objects (facts, registered variables) now have a different structure from CVP, which users may not expect
2. The filters and remapping of keys (as in the case of tasks) creates confusion as the same piece of code `tasksField` dict now needs to be updated in multiple modules, e.g. cv_fact, cv_configlet, cv_device, i.e. anything that can generate a task object.

I may not know the initial reason for doing this filtering but can I suggest we discuss going back to just copying objects as-is, without modifications. This way we don't create unnecessary circular dependencies between modules and reduce some of the code complexity.

**Comment by titom73** [comment]
It creates same constraints for `device` and `configlet`: each time we have to call an API, we have to rebuild a valid structure to be compliant with what CVP expect.

Using JSON facts as sent by CVP would reduce number of call to API and reduce code complexity as well as time execution.

**Comment by titom73** [comment]
From issue #31 

Under certain circumstances, collecting device configuration in `cv_facts` dramatically increase execution time:

Device configured in provisioning but not accessible.
```
Gather CVP facts from cvp_foster --- 198.20s
```

Device not configured in provisioning and accessible:
```
Gather CVP facts from cvp_foster --- 13.92s
```

because device configuration is not a must have for CVP provisionning, we might disable collecting configuration for devices or configure a timeout to not increas too much time execution.

__Tested with__
- CVP foster
- cv_facts from `grant-release`

**Comment by titom73** [comment]
From Issue #32 : Implement filter in `cv_facts`

One more thing that might be useful is to be able to filter what type of facts you want to collect. for example, if you expect only tasks to have changed, then it should be possible to run cv_facts with something like `filter: tasks` to only make it update tasks.
