### ISSUE TITLE
[Security] Workflow continuous_integration.yml is using vulnerable action pre-commit/action

### ISSUE THREAD

**Issue by Ale0x78** [aristanetworks/ansible-cvp#432]
The workflow continuous_integration.yml is referencing action pre-commit/action using references v2.0.2. However this reference is missing the commit [80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by mtache** [comment]
Hi !

Actually, tags on the repo https://github.com/pre-commit/action are only made on the `release` branch that contains the output of webpack (with the exception of tag v2.0.1, some mistake ?). IMHO, this is quite problematic because we will never be sure that the code committed in the `master` branch is actually included in the bundled/minified code (webpack output) in the `release` branch.

Back to your issue, the version 2.0.2 **should** include the new dependancies specified in the commit [80db042](https://github.com/pre-commit/action/commits/80db042ff08cdddbbbfb6f89c06a6bfc4dddf0b7) because the author did [this commit (60a9f2e)](https://github.com/pre-commit/action/commit/60a9f2e5ef9fcb955fa83b6293fcc8dbb876b1b7) later in the history. However, this is only based on the trust that the author actually built [the tag v2.0.2](https://github.com/pre-commit/action/releases/tag/v2.0.2) that points to the commit [9cf68dc](https://github.com/pre-commit/action/commit/9cf68dc1ace5504cd0e05b9f3df32e6a0822ad89) on the `release` branch with the code versioned at [60a9f2e](https://github.com/pre-commit/action/commit/60a9f2e5ef9fcb955fa83b6293fcc8dbb876b1b7), and we cannot be sure of that (unless maybe by webpacking the source and comparing the dist/index.js files).

Anyway, https://github.com/pre-commit/action is deprecated. Maybe moving to pre-commit.ci or just a simple script will put things right. This is a discussion to have with the maintainers.

Thanks
